---
# playbook to import kerberos keytab files
# Example:
#   import_keytab_files:
#     - file: uploads/kerberos/kerberos.krb5
- hosts: "{{ hosts | default('all')}}"
  gather_facts: no
  connection: local
  roles:
    - role: web/import_keytab_files
      tags: import_keytab_files
