---
# update
#   update jmt files
#   Example:
#     jmt_files
#       - file: uploads/jmt/jmt.conf
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: web/update_jmt_files
      tags: update_jmt_files
