---
# upload
#   upload ltpa files
#   Example:
#     jmt_files
#       - file: uploads/ltpa/default.ltpa
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: web/upload_ltpa_files
      tags: upload_ltpa_files
