---
# upload
#   upload management root files
#   Example:
#     management_root_files:
#         -   instance_id: default
#             filename: "uploads/management_root/management/C/example.html"
#             target: "management/C/example.html"
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: web/upload_management_root_files
      tags: upload_management_root_files
