# main task: load_signer_certificates
---
- name: Load signer certificates into certificate store
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: ibmsecurity.isam.base.ssl_certificates.signer_certificate.load
    isamapi:
      kdb_id: "{{ item.kdb_id }}"
      label: "{{ item.label }}"
      server: "{{ item.server }}"
      port: "{{ item.port }}"
  with_items: "{{ load_signer_certificates }}"
  notify: Commit Changes
