---
# task file for ISAM appliance first steps
#
#     accept service agreements
#     set up LMI FIPS
#     commit and restart appliance
#
# accept service agreements
- name: Accept Service Agreements
  ibm.isam.isam:
    action: ibmsecurity.isam.base.service_agreement.set

# set up LMI FIPS
- name: Setup FIPS Mode
  ibm.isam.isam:
    action: ibmsecurity.isam.base.fips.set
    isamapi:
        fipsEnabled: "{{ FIPS_cfg.fipsEnabled }}"
        tlsv10Enabled: "{{ FIPS_cfg.tlsv10Enabled }}"
        tlsv11Enabled: "{{ FIPS_cfg.tlsv11Enabled }}"
  register: ret_obj
  when:
    - FIPS_cfg is defined
    - FIPS_cfg.fipsEnabled
    - first_steps_fips|bool

# Restart after FIPS if needed
- name: Restart after enabling FIPS
  ibm.isam.isam:
    action: ibmsecurity.isam.base.fips.restart_and_wait
  when:
    - first_steps_fips
    - ret_obj.data.reboot is defined
    - ret_obj.data.reboot

# Complete the appliance set up
- name: Complete Appliance Setup
  ibm.isam.isam:
    action: ibmsecurity.isam.base.setup_complete.set

  ibm.isam.isam:
    action: ibmsecurity.isam.base.admin.set_pw
    isamapi:
        'oldPassword': 'admin'
        'sessionTimeout': "{{ lmi_session_timeout }}"
  when: first_steps_admin_pwd

# Commit changes and restart LMI
- name: Commit Changes and Restart LMI
  ibm.isam.isam:
    action: ibmsecurity.isam.appliance.commit_and_restart_and_wait
