---
# Add
#   add interfaces by following inventory structure:
#   Example:
#      activation_keys:
#        - id: wga
#          code: "AAAA-BBBB-CCCC-DDDD-EEEE"
- hosts: "{{ hosts | default('all')}}"
  gather_facts: no
  roles:
    - role: ibm.isam.base/activate_modules
      tags: activate_modules
