---
# Change
#   change appliance admin user password
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: base/change_admin_password
      tags: change_admin_password