---
# Change
#   change appliance admin user password
- hosts: "{{ hosts | default('all')}}"
  gather_facts: no
  roles:
    - role: ibm.isam.base/change_admin_password
      tags: change_admin_password
