---
# Configure
#   configure runtime tuning parameters
#   Example:
#     runtime_tuning:
#         - option: http_proxy_host
#           value: ibm.com
- hosts: "{{ hosts | default('all')}}"
  serial: "{{ serial | default('100%')}}"
  gather_facts: no
  roles:
    - role: ibm.isam.base/configure_runtime_tunings
      tags: configure_runtime_tunings
