---
# Create
#   create sysaccounts
#     sysaccounts:
#        - id: sec_master
#          password: "{{ basicauth_dummy_passwd }}"
#          groups: []
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: base/create_sysaccounts
      tags: create_sysaccounts