---
# Set
#   Set host entries
#   Example:
#      host_records:
#        - addr: 192.168.0.1
#          hostnames:
#            - isam.ibm.com
- hosts: "{{ hosts | default('all')}}"
  gather_facts: no
  roles:
    - role: ibm.isam.base/set_host_records
      tags: set_host_records
