---
# Set
#   set listening interfaces
#   Example:
#      listening_interfaces:
#        - interface: 192.168.0.1
#          port: 443
#          secure: 'yes'
- hosts: "{{ hosts | default('all')}}"
  gather_facts: no
  roles:
    - role: ibm.isam.base/set_listening_interfaces
      tags: set_listening_interfaces
