---
# Add
#   add interfaces by following inventory structure:
#   Example:
#      updates:
#        - file: uploads/updates/90x.pkg
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: base/upload_updates
      tags: upload_updates
      