# Default variables for configuration of management root content
instances: []

# variables to control whether to configure one instance and/or one target at a time or everything from the configurations
inst_name: "{{ item.0.inst_name if (item is defined) }}"
file: "{{ item.1.file if (item is defined and item.1 is defined and item.1.file is defined) }}"
# directory: "{{ item.1.directory if (item is defined and item.1 is defined and item.1.directory is defined) }}"
target: "{{ item.1.target | default(omit) }}"
filename: "{{ (inventory_dir + '/' + item.1.file) if (item.1.file is defined) }}"

# No filter at runtime on mgmt_action if none is defined. This will try every feasable action in the play
mgmt_action: "None" 

# Do not delete any files as default behavior
delete_missing: false

# do not skip import tasks by default
skip_imports: false
skip_exports: false
