---
# create
#   set point of contact profile:
#    set_current_point_of_contact_name: Non-Access Manager Username, Access Manager groups and extended attributes

- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: set_current_point_of_contact
      tags: set_current_point_of_contact