---
# create
#   set user registry user password
#       set_ldap_user_pwd_id: easuser
#       set_ldap_user_pwd_password: "{{ easuser_password }}"
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: set_ldap_user_pw
      tags: set_ldap_user_pw