---

- name: Verify - add
  hosts: all
  gather_facts: no
  tasks:
    - include_vars:
        file: "../../vars/main.yml"
        name: inventory

    - name: "Get the authentication mechanism {{ inventory.molecule.name }}"
      include_role:
        name: "get_authentication_mechanisms"
      vars:
        get_authentication_mechanisms:
          - name: "{{ inventory.molecule.name }}"

    - name: "Assert that the authentication mechanism {{ inventory.molecule.name }} was added"
      assert:
        that: ret_obj.results.0.data.name == inventory.molecule.name
        fail_msg: "Authentication Mechanism {{ inventory.molecule.name }} was not added"
        success_msg: "Authentication Mechanism {{ inventory.molecule.name }} was added"
