# Create a Report on Memory Usage

- name: Get Memory Details
  hosts: all
  no_log: True
  vars:
    log_level: "CRITICAL"
  roles:
    - role: ibm.isam.start_config
      start_config_skip_pending_check: True
      start_config_skip_snapshot:      True

    - role: ibm.isam.get_memory_statistics
      statistics_duration: "6d"

    - role: ibm.isam.gen_report
      gen_report_template: "report_memory_statistics.csv"
      gen_report_dir: "~"
