---
# Archive logs in Reverse Proxy

- name: Archive Reverse Proxy Logs
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - role: start_config

    - role: archive_logs
      archive_logs_instance_id: "{{ reverseproxy_instance_name }}"
      archive_logs_directory: "/tmp"
      archive_logs_delete: False