---
# Restart reverse proxy that need it, pass variable force as True to force restarts
- name: Restart Reverse Proxy
  hosts: all
  gather_facts: no
  roles:
    - role: ibm.isam.start_config

  tasks:
    - debug: msg="Trigger Reverse Proxy restarts"
      changed_when: True
      notify: Restart Reverse Proxy

