---
# Configure
#   configure user_registry
#   Example:
#     user_registry:
#       - action: set_pw
#         id: easuser
#         password: *****
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: aac/configure_user_registry
      tags: configure_user_registry
