---
# Configure
#   configure server connections
#   Example:
#      server_connections:
#       -   name: server_connection_1
#           class: ldap
#           connection:
#             bindDN:   cn=root
#             bindPwd:  "{{ pwd }}"
#             hostName: ldap.ibm.com
#             hostPort: 389
#             ssl: false
#           description: Demo Connection to LDAP
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: aac/configure_server_connections
      tags: configure_server_connections
      