---
# Configure
#   configure api protection definitions
#   Example:
#     api_protection:
#       definitions:
#         - name: oauth-provider
#           description: API protection for OAuth service provider
#           grantTypes:
#             - AUTHORIZATION_CODE
#           tcmBehavior: NEVER_PROMPT
#           clients: 
#             - name: TestApp
#               companyName: IBM demo client for OAuth flows
#               redirectUri: https://localhost
#               contactType: ADMINISTRATIVE
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: aac/configure_api_protection_clients
      tags: configure_api_protection_clients
      